M48
; DRILL file {KiCad 9.0.6+1} date 2026-01-21T18:48:14+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-21T18:48:14+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.600
%
G90
G05
T1
X200.21Y-191.695
X205.99Y-191.695
T2
X240.37Y-122.03
T3
X231.56Y-124.57
M30
